language: minimal

services: docker

env:
  - CONTAINER_IMAGE=blog-restapi-users

before_install: 
  - sudo apt update -y
  - sudo apt install realpath python python-pip -y
  - sudo apt install --only-upgrade docker-ce -y
  - sudo pip install docker-compose || true
  - docker info
  - docker-compose --version

script:
  - docker pull $CONTAINER_IMAGE:latest || true
  - >
      docker build
      --pull
      --cache-from $CONTAINER_IMAGE:latest
      --tag $CONTAINER_IMAGE:latest
      .
  - docker tag $CONTAINER_IMAGE:latest $CONTAINER_IMAGE:latest
  - docker push $CONTAINER_IMAGE