language: minimal

services: docker

stages:
  - package


env:
  - CONTAINER_IMAGE=blog-restapi-users

before_install: 
  - sudo apt update -y
  - sudo apt install realpath python python-pip -y
  - sudo apt install --only-upgrade docker-ce -y
  - sudo pip install docker-compose || true
  - docker info
  - docker-compose --version

docker-build:
  stage: package
  before_script:
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  after_script:
    - docker logout
  script:
    # fetches the latest image (not failing if image is not found)
    - docker pull $CONTAINER_IMAGE:latest || true
    # builds the project, passing proxy variables, and vcs vars for LABEL
    # notice the cache-from, which is going to use the image we just pulled locally
    # the built image is tagged locally with the commit SHA, and then pushed to
    # the GitLab registry
    - >
      docker build
      --pull
      --cache-from $CONTAINER_IMAGE:latest
      --tag $CONTAINER_IMAGE:latest
      .
    - docker tag $CONTAINER_IMAGE:latest $CONTAINER_IMAGE:latest
    - docker push $CONTAINER_IMAGE



  