language: minimal

services: docker

env:
  - APP_NAME="jcnegrin/blog-restapi-users"

before_install: 
  - sudo apt update -y
  - sudo apt install realpath python python-pip -y
  - sudo apt install --only-upgrade docker-ce -y
  - sudo pip install docker-compose || true
  - docker info
  - docker-compose --version

script:
  - docker build -t $APP_NAME .

after_success:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD ;
  - docker push $APP_NAME
  - docker logout